### ISSUE TITLE
操作历史的技术选型

### ISSUE THREAD

**Issue by ifyouseewendy** [ifyouseewendy/duoduo#44]
- paper_trail https://github.com/airblade/paper_trail
- audited https://github.com/collectiveidea/audited
- public_activity https://github.com/chaps-io/public_activity

**Comment by ifyouseewendy** [comment]
[Activity Feeds with Rails](http://www.sitepoint.com/activity-feeds-rails/)

> In some ways, paper_trail is similar to public_activity and could be used to implement a solution similar to the one presented in this article. However, paper_trail is aimed at crafting versioning systems, whereas public_activity was created specifically to implement activity feeds.

**Comment by ifyouseewendy** [comment]
**结论**

使用 public_activity。只做操作历史的记录，而不基于操作历史做『撤销』等操作。

**操作记录**

每条记录包含如下信息：`{user} {opt} {object} {time_at}`
- `user`，为 AdminUser
- `opt`，默认为 create, update, destroy；
- `object`，系统中所有 model

**自定义操作**

自定义操作需要在相应操作处创建 key，并添加 i18n 支持

``` ruby
@article.create_activity key: 'article.commented_on', owner: current_user, parameters: {}
```

**Comment by ifyouseewendy** [comment]
**TODO**
- [x] 配置 public_activity
- [x] 为 Project model 添加操作历史
- [x] 添加 activity 为 AA 资源，并显示、过滤
- [x] 参照 Project 为其他 model 添加 public_activity 集成
